---
- name: ensure timezone is set in apache2 php.ini
  become: yes
  lineinfile: dest=/etc/php/{{ php.version }}/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache
  become: yes
  lineinfile: dest=/etc/php/{{ php.version }}/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'
- name: print debug information
  debug:
    msg: "PHP version: {{ php.version }}" 	
  
- name: pcre_jit
  become: yes
  when: php.version > 7
  lineinfile:
    dest: /etc/php/{{ php.version }}/apache2/php.ini
    regexp: '^pcre.jit ='
    line: 'pcre.jit = {{ php.pcre_jit }}'
  notify:
    - restart apache

- name: display errors
  become: yes
  lineinfile:
    dest: /etc/php/{{ php.version }}/apache2/php.ini
    regexp: '^display_errors ='
    line: 'display_errors = {{ php.display_errors }}'
  notify:
    - restart apache
