---
- name: ensure timezone is set in cli php.ini
  become: yes
  lineinfile: dest=/etc/php/{{ php.version }}/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache cli
  become: yes
  lineinfile: dest=/etc/php/{{ php.version }}/cli/php.ini
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: pcre_jit_cli
  become: yes
  when: php.version > 7
  lineinfile:
    dest: /etc/php/{{ php.version }}/cli/php.ini
    regexp: '^pcre.jit ='
    line: 'pcre.jit = {{ php.pcre_jit }}'
  notify:
    - restart apache
